### ISSUE TITLE
Assignment number

### ISSUE THREAD

**Issue by AliZafar120** [IITDU-BSSE06/ads-demystifying-the-logs-AliZafar120#1]
@LordAmit Sir,
There is no number associated with the given assignments, however submission folder has number. Will we we consider them chronologically and submit?

**Comment by AliZafar120** [comment]
And Sir do we need to provide steps or only mapper and reducer python/java code?

**Comment by LordAmit** [comment]
Good point! Yes, the tasks in bullet points should be considered in order. 

About your second question, it is a programming assignment, that talks about code. Steps simply won't do.
